### ISSUE TITLE
Color picker needs to reflect color

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/tt4-dark-mode#1]
I forgot about this one, but we do need a tiny bit of Editor CSS:

```css
.components-circular-option-picker__option-wrapper {
	color-scheme: light dark;
}
```

This ensures that the color picker uses the right color scheme:

![tt4-dark-color-picker](https://github.com/user-attachments/assets/7c95f230-b931-43f8-8180-32ff8b371dff)
